spring:
  application:
    name: all-service
  datasource:
    url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf8&mysqlEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456


server:
  port: 8762

# mybatis配置================================
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true # 开户驼峰规则转换

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/