
spring:
  application:
    name: app-backend

server:
  port: 8280

# 配置注册与发现服务 ========================
eureka:
  client:
    registryFetchIntervalSeconds: 5
    enabled: true # 是否启用注册服务 默认为true, false是不启用
    service-url:
      defaultZone: http://localhost:8771/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true

custom:
  data:
    gateway:
      host: http://localhost:8762

logging:
  file: var/log/app-backend.log
  level:
    com:
      todo:
        system:
          backend: DEBUG






